// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBypxbDZ9OxDHmTz7kSf5JSGe4WawrPjh4',
    appId: '1:233542072050:web:2bbe43f145b273e1a4026b',
    messagingSenderId: '233542072050',
    projectId: 'desarrollo-movil-taviz',
    authDomain: 'desarrollo-movil-taviz.firebaseapp.com',
    storageBucket: 'desarrollo-movil-taviz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8cNGJA8JCH9DdnUrZMZ6Fp3Q2Lp6IL0g',
    appId: '1:233542072050:android:5f0fcc7ca45ba80ea4026b',
    messagingSenderId: '233542072050',
    projectId: 'desarrollo-movil-taviz',
    storageBucket: 'desarrollo-movil-taviz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOqbvpk8XGLk-r-88YdjBy8JTPSf4tL_U',
    appId: '1:233542072050:ios:22d3cce12f28e51da4026b',
    messagingSenderId: '233542072050',
    projectId: 'desarrollo-movil-taviz',
    storageBucket: 'desarrollo-movil-taviz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOqbvpk8XGLk-r-88YdjBy8JTPSf4tL_U',
    appId: '1:233542072050:ios:22d3cce12f28e51da4026b',
    messagingSenderId: '233542072050',
    projectId: 'desarrollo-movil-taviz',
    storageBucket: 'desarrollo-movil-taviz.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBypxbDZ9OxDHmTz7kSf5JSGe4WawrPjh4',
    appId: '1:233542072050:web:0c358b5e0fc943b6a4026b',
    messagingSenderId: '233542072050',
    projectId: 'desarrollo-movil-taviz',
    authDomain: 'desarrollo-movil-taviz.firebaseapp.com',
    storageBucket: 'desarrollo-movil-taviz.firebasestorage.app',
  );
}
